# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: UN ELECTRONICA
email: mdchaparror@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jugando con la electrónica 

include: ['_pages']
  
  
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://unelectronica.github.io" # the base hostname & protocol for your site
url: "192.168.1.105" # the base hostname & protocol for your site
#destination: miPagina
#sidebar
default-image: unel.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: mdchaparror
copyright:
   name: mdchaparror
   link: 'http://mdchaparror.github.io'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: UA-97046731-1

# Comments
disqus-shortname: mdchaparror-github-io

#social
#facebook: http://facebook.com/mdchaparror
#quora: http://quora.com/sharathdt
twitter: http://twitter.com/@mdchaparror
github: http://github.com/unelectronica

#facebook like box
#fb-app-id: 549480635219583
#fb-page-url: https://www.facebook.com/webjeda/
#fb-page-title: webjeda

# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]

